# Generated by Django 4.2.1 on 2023-06-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_etheraccountcustomer_etheraccountcardealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='smart_contract_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etheraccountcardealer',
            name='car_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cardealer'),
        ),
    ]
