# Generated by Django 4.2.1 on 2023-06-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TX_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.order')),
            ],
        ),
    ]
